data<-subset(read.table("household_power_consumption.txt",header=TRUE,na.strings="?",sep=";"),Date=="1/2/2007"|Date=="2/2/2007")
data$Fecha<-strptime(paste(data$Date,data$Time),"%d/%m/%Y %H:%M:%S")
Sys.setlocale("LC_TIME","English")
png(file="plot3.png")
with(data,plot(Fecha,Sub_metering_1,type="n",xlab="",ylab="Energy sub metering"))
    with(data,lines(Fecha,Sub_metering_1))
    with(data,lines(Fecha,Sub_metering_2,col="red"))
    with(data,lines(Fecha,Sub_metering_3,col="blue"))
    legend("topright",lwd=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()

