data<-subset(read.table("household_power_consumption.txt",header=TRUE,na.strings="?",sep=";"),Date=="1/2/2007"|Date=="2/2/2007")
data$Fecha<-strptime(paste(data$Date,data$Time),"%d/%m/%Y %H:%M:%S")
Sys.setlocale("LC_TIME","English")
png(file="plot4.png")
par(mfrow=c(2,2))
with(data,{
     plot(Fecha,Global_active_power,type="l",xlab="",ylab="Global Active Power")
     plot(Fecha,Voltage,type="l",xlab="datetime",ylab="Voltage")
     plot(Fecha,Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
        with(data,lines(Fecha,Sub_metering_1))
        with(data,lines(Fecha,Sub_metering_2,col="red"))
        with(data,lines(Fecha,Sub_metering_3,col="blue"))
        legend("topright",lwd=1,bty="n",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
    plot(Fecha,Global_reactive_power,type="l",xlab="datetime")
})    
dev.off()